# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  github_client_id:      <%= ENV['GITHUB_CLIENT_ID']      %>
  github_client_secret:  <%= ENV['GITHUB_CLIENT_SECRET']  %>
  google_analytics_id:   <%= ENV['GA_ANALYTICS_ID']       %>
  bugsnag_api_key:       <%= ENV['BUGSNAG_API_KEY']       %>
  bugsnag_js_api_key:    <%= ENV['BUGSNAG_JS_API_KEY']    %>
  github_webhook_secret: <%= ENV['GITHUB_WEBHOOK_SECRET'] %>
  github_app_id:         <%= ENV['GITHUB_APP_ID']         %>
  github_app_client_id:      <%= ENV['GITHUB_APP_CLIENT_ID']      %>
  github_app_client_secret:  <%= ENV['GITHUB_APP_CLIENT_SECRET']  %>

development:
  <<: *default
  secret_key_base: 6e36f2ef31409ba2199a632ca8437a527407b89bf6d983365fb3e5c0d3b7ad9e47af6565d737a8770faf5e82a7e01a97aac6a653362397d0429d6f590a249515

test:
  <<: *default
  secret_key_base: 0c04521fa37d6d3452a84bb7b94e5fcccbf1e292b4f3345fd576b2f4c101c2559fa02be9ce3a9e5badd156006569f2074c044f5c1516bf85b2a1c8834a4c466b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
